### ISSUE TITLE
Does the upgrade instruction work for 9.5-x to 9.6-x?

### ISSUE THREAD

**Issue by grandtiger** [sameersbn/docker-postgresql#108]
I have been running version 9.5-x for a long time and it's working well. But I would like to upgrade to 9.6-x and wonder what is the correct procedure to do so. Does the upgrade instruction work for 9.5-x to 9.6-x? 

My database has grown to over 200GB, so I don't want to risk losing all the data. My goal is to preserve all the data. If that's not possible, then I would like to keep data migration effort minimum.

Thanks a lot for any help/tips you may provide!

**Comment by leonsp** [comment]
Going from `9.5` to `9.6` worked for me, but I had a lot less data than 200GB. Data migration takes a while, so allow a long time for the container to start

I highly recommend having a backup (pg_dump) before starting. Restoring Postgres backups is pretty easy

**Comment by grandtiger** [comment]
@leonsp Thanks for sharing your experience! I will give it a try!
