### ISSUE TITLE
Release for PostgreSQL 10

### ISSUE THREAD

**Issue by nigredo-tori** [sameersbn/docker-postgresql#116]
PostgreSQL 10 is out since October, so we should probably upgrade (maybe in a different branch?)

**Comment by nigredo-tori** [comment]
Closing this, since the version for PG 10 is out.

@grandtiger, as far as I understand, this image detects the data for old Postgres versions in the data volume, and runs pg_upgrade automatically. Upgrading *should* be as easy as switching to the new image. But you should back everything up beforehand, obviously.

**Comment by geberl** [comment]
@grandtiger I just mounted the data-volume from my old Postgres 9.6 container on run of the new Postgres 10 container. This installed the old postgres9.6 packages and migrated my data. Search for `PG_OLD_VERSION` in `docker-postgresql/runtime/functions` to see the commands.
