### ISSUE TITLE
Docker tag for latest version of given Postgres line

### ISSUE THREAD

**Issue by szpak** [sameersbn/docker-postgresql#131]
## Feature description
It would be nice to have a dedicated Docker tags for latest version of given Postgres line.

## Detailed information
It's good that you make tag for every new image release (instead of using just latest :) ), but it could be handy to be able to put `sameersbn/postgresql:10` or `sameersbn/postgresql
:11` in the Docker configuration to stay with the latest version of Postgres with a given line (to not end up with Postgres 12 having an application not compatible with it).

That would require to name the first release 11-1, followed by 11-2, 11-3 while the tag 11 (or `11-latest` at your preference) would be reserved for the latest release of 11.x. Of course `latest` would be the latest version in general.

What do you think about that?

Btw, thanks for developing that container! I've found it very useful, especially the `ENABLE_PLUGINS` parameter.

**Comment by sameersbn** [comment]
after migrating to github actions, the rolling release tag is now available
