### ISSUE TITLE
upgrade from 9.1 to 9.4 failed

### ISSUE THREAD

**Issue by smoebody** [sameersbn/docker-postgresql#16]
when i try to start a container with the latest image and an already existing database (gitlabhq_production) the migration process failed with the following messages in `pg_upgrade_server.log`:

    command: "/usr/lib/postgresql/9.1/bin/pg_ctl" -w -l "pg_upgrade_server.log" -D "/var/lib/postgresql/9.1/main" -o "-p 50432 -b -c config_file=/etc/postgresql/9.1/main/postgresql.conf -c listen_addresses='' -c unix_socket_permissions=0700 -c unix_socket_directory='/var/lib/postgresql'" start >> "pg_upgrade_server.log" 2>&1
    waiting for server to start.....2015-02-16 13:16:35 UTC [972-1] FATAL:  could not create shared memory segment: Invalid argument
    2015-02-16 13:16:35 UTC [972-2] DETAIL:  Failed system call was shmget(key=50432001, size=41205760, 03600).
    2015-02-16 13:16:35 UTC [972-3] HINT:  This error usually means that PostgreSQL's request for a shared memory segment exceeded your kernel's SHMMAX parameter.  You can either reduce the request size or reconfigure the kernel with larger SHMMAX.  To reduce the request size (currently 41205760 bytes), reduce PostgreSQL's shared memory usage, perhaps by reducing shared_buffers or max_connections.
        If the request size is already small, it's possible that it is less than your kernel's SHMMIN parameter, in which case raising the request size or reconfiguring SHMMIN is called for.
        The PostgreSQL documentation contains more information about shared memory configuration.
    ... stopped waiting
    pg_ctl: could not start server
    Examine the log output.

**Comment by sameersbn** [comment]
@smoebody this has something to do with the system configuration as mentioned in the error message. Please try looking up for the error resolution on google.

Let me know if you need any assistance once you are able to locate a fix.

**Comment by smoebody** [comment]
after research i found [this][1] but changing that value on the hostsystem will not propagate to the docker containers.
hostsystem:

    #$ cat /proc/sys/kernel/shmmax 
    268435456

container:

    #$ cat /proc/sys/kernel/shmmax 
    33554432

trying to change the size in the container tells me the following

    #$ sysctl -w kernel.shmmax=268435456
    sysctl: setting key "kernel.shmmax": Read-only file system

any suggestions are appreciated
  
[1]: https://yuji.wordpress.com/2011/11/03/postgresql-could-not-create-shared-memory-segment-invalid-argument-shmget/

**Comment by sameersbn** [comment]
@smoebody can you try changing the `shmax` configuration after starting the container in privileged mode i.e. `--privileged=true`. If it works, then you can add the `shmax` configuration in the `start` script and build the image so that the migration can go through. Once you have the migration completed you can go back to using the `sameersbn/postgresql` image.

Btw, what is the available memory on your host. Interesting for me `cat /proc/sys/kernel/shmmax` show the same number for me whether I do it on the host or the container.

**Comment by smoebody** [comment]
@sameersbn thanks for the hint. `--privileged` did the trick.

what i did:

    docker-host#$ docker run -ti --rm -v /path/to/dbfiles:/var/lib/postgresql --privileged=true --entrypoint=bash -e "DB_NAME=gitlabci_production,gitlabhq_production" sameersbn/postgresql:latest
    docker-container#$  sysctl -w kernel.shmmax=268435456
    kernel.shmmax = 268435456
    docker-container#$ /start
    ...

the database migration went through flawlessly, and after that i could run a unprivileged production container.

my host has 8GB memory available, my os is ubuntu 14.04.1 LTS, kernel is 3.13.0, docker version is 1.4.1, build 5bc2ff8.

im running 11 docker containers, all with shmmax=33554432. dont know where this restriction is coming from.

anyways, thanks for your help.
