### ISSUE TITLE
cannot enable hstore extension using sameersbn/postgresql:9.4

### ISSUE THREAD

**Issue by yachi** [sameersbn/docker-postgresql#19]
```
docker run --rm -it sameersbn/postgresql:9.4 ls /usr/share/postgresql/9.4/extension/hstore.control
```

ls: cannot access /usr/share/postgresql/9.4/extension/hstore.control: No such file or directory

But it works fine if i build it myself

**Comment by sameersbn** [comment]
@yachi I think that file comes from the `postgresql-contrib` package which was added in 9cca232ba0ec653b7bbcf84a5b1b8c4bf262e284 and that is after version `9.4` was tagged. If you need the particular file to existing then please use the `latest` tag, or build the image locally (which is the same as using the latest tag), or wait until `9.4-1` is released.

**Comment by yachi** [comment]
Thanks!
Btw your documentation is much better than the official one :+1:
