### ISSUE TITLE
cannot initialize the database

### ISSUE THREAD

**Issue by jshridha** [sameersbn/docker-postgresql#20]
With a fresh pull of the docker I get this error message:

<code>Initializing database...
LOG: could not link file "pg_xlog/xlogtemp.31" to "pg_xlog/000000010000000000000001" (initialization of log file): Function not implemented
FATAL: could not open file "pg_xlog/000000010000000000000001": No such file or directory
child process exited with exit code 1
initdb: removing data directory "/var/lib/postgresql/9.4/main"</code>

This is the command I'm using to start the docker:
<code>docker run --name=postgresql -d \
  -e 'DB_NAME=gitlabhq_production' -e 'DB_USER=gitlab' -e 'DB_PASS=password' \
  -v /mnt/user/appdata/postgresql:/var/lib/postgresql \
  sameersbn/postgresql:latest</code>

**Comment by jshridha** [comment]
I thought I had tested everything before posting the issue. It turns out the problem was with my filesystem. This looks to be specific to my setup.

**Comment by InAnimaTe** [comment]
If anyone else is reading this, and if the reported is also running UnRaid (which I presume he is based on his host directory path), then I figured out what is going on.

It seems the `shfs` fuse based filesystem unraid uses to provide user shares disagrees with postgresql. Sadly, this means you can't use a user share. However, from [here](https://lime-technology.com/wiki/index.php/Cache_disk#The_Mover), it appears you can make a hidden directory in your cache pool that won't actually get moved. Hence, I just made `/mnt/cache/.jira-postgresql` and was on my way :)

**Comment by soundless** [comment]
It's very helpful, thank you.
