### ISSUE TITLE
Support master/slave configuration flags

### ISSUE THREAD

**Issue by Downchuck** [sameersbn/docker-postgresql#24]
Great example here for enabling master/slave replication:
https://github.com/hmarr/docker-postgresql

**Comment by sameersbn** [comment]
@Downchuck Will check it out soon. Thanks

**Comment by Downchuck** [comment]
Checking in... Should I try for a pull request?

**Comment by sameersbn** [comment]
@Downchuck Completely forgot about this, I'm sorry.

> Should I try for a pull request?
Sure, that would be perfect.

**Comment by Downchuck** [comment]
I've submitted a pull request -- it seems like SSL support is something to look at, in the future. For now, replication seems to be working, I tested it within a server using docker inspect to get the IP address of the master instance.

**Comment by sameersbn** [comment]
https://github.com/sameersbn/docker-postgresql/commit/9dd5b55b3ade7f19ebef83c8bdf507ada293e61c closes this issue
