### ISSUE TITLE
chown: changing ownership of '/var/lib/postgresql': Permission denied

### ISSUE THREAD

**Issue by lyongde** [sameersbn/docker-postgresql#25]
docker-postgresql doesn't work in CentOS 7.

#docker version
Client version: 1.5.0-dev
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): fc0329b/1.5.0
OS/Arch (client): linux/amd64
Server version: 1.5.0-dev
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): fc0329b/1.5.0
OS/Arch (server): linux/amd64

#docker info
Containers: 1
Images: 41
Storage Driver: devicemapper
 Pool Name: docker-253:1-273367750-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.213 GB
 Data Space Total: 107.4 GB
 Data Space Available: 99.64 GB
 Metadata Space Used: 2.294 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 3.631 GiB
Name: localhost.iginwa2
ID: 32ND:J7M7:PEKE:5BV4:PUFD:SQRZ:PEIY:ADCG:3FRS:T6RN:OTKF:TKEQ

#docker run --name=gitlab_postgresql -d \
  -e 'DB_NAME=gitlabhq_production' \
  -e 'DB_USER=gitlab' \
  -e 'DB_PASS=password' \
  -v /opt/gitlab/postgresql:/var/lib/postgresql \
  sameersbn/postgresql:latest

#docker logs gitlab_postgresql
chown: changing ownership of '/var/lib/postgresql': Permission denied

**Comment by sameersbn** [comment]
@lyongde This is most definitely selinux playing spoilsport. Did you follow the selinux related [instructions](https://github.com/sameersbn/docker-postgresql#data-store)? If that does not fix the issue, turn off selinux `setenforce 0` and check if it works. If this fixes the issue, then you can either permanently disable selinux :fearful: or look for the solution in some centos/fedora forum.

**Comment by lyongde** [comment]
thanks, I fix the issue follow https://github.com/sameersbn/docker-postgresql#data-store.
