### ISSUE TITLE
db not created with tag 9.1

### ISSUE THREAD

**Issue by ilkosta** [sameersbn/docker-postgresql#26]
When I run
"""
docker run --name postgresql -d   -e 'DB_USER=dbuser' -e 'DB_PASS=dbpass' -e 'DB_NAME=dbname'   sameersbn/postgresql:9.1

docker exec -it postgresql su postgres -c "psql -l"
"""

the "dbname" db is not present.

**Comment by sameersbn** [comment]
@ilkosta This feature was release in `9.1-1`. If you want to use `postgresql-9.1` you are should use the image tagged `9.1-2`.

**Comment by ilkosta** [comment]
thanks a lot!
