### ISSUE TITLE
How to stop the database properly ?

### ISSUE THREAD

**Issue by wichtounet** [sameersbn/docker-postgresql#31]
Hi, 

First of all, thanks for the create script :)

Using this how do you stop your container ? Simply using 'docker stop name' ? If I do that, I have the message: 

LOG:  database system was interrupted; last known up at 2015-06-08 04:28:10 GMT
LOG:  database system was not properly shut down; automatic recovery in progress

Is that normal ? 

I have adapted your script for Gentoo, so maybe there are differences or I have made a mistake causing this. 

Thanks

**Comment by sameersbn** [comment]
@wichtounet `docker stop name` should gracefully shutdown the postgresql server. This is what  you should see in the logs when you start the container again.

```bash
Starting PostgreSQL server...
2015-06-08 04:17:30 UTC [26-1] LOG:  database system was shut down at 2015-06-08 04:17:30 UTC
2015-06-08 04:17:30 UTC [1-1] LOG:  database system is ready to accept connections
2015-06-08 04:17:30 UTC [30-1] LOG:  autovacuum launcher started
```

> Is that normal ?

No, what you are seeing is not normal. When you stop the container, you can check the exit code of the container in the `docker ps -a | grep name`. On a clean shutdown the exit code will be `0`.

**Comment by wichtounet** [comment]
Thanks for your answer, it was coming from sudo not passing the signal correctly to postgresq. It is perfect now.
