### ISSUE TITLE
initdb: could not create directory "/var/lib/postgresql/9.4/main": Permission denied

### ISSUE THREAD

**Issue by mrh666** [sameersbn/docker-postgresql#34]
Can't start postgres container on Mac OS, docker 1.6.2:

```
> mkdir -p /Users/username/docker-gitlab/postgresql && chmod 0777 /Users/username/docker-gitlab/postgresql

> docker run --privileged --name=postgresql-gitlab -d   --env='DB_NAME=gitlabhq_production'  --env='DB_USER=gitlab' --env='DB_PASS=password'  --volume=/Users/username/docker-gitlab/postgresql:/var/lib/postgresql   sameersbn/postgresql:9.4
1334c50d0e2fa75afa4f491a8d2f62baab52042efe76240e0a01592d23ee404b

> docker ps -a
CONTAINER ID        IMAGE                      COMMAND             CREATED             STATUS                     PORTS               NAMES
1334c50d0e2f        sameersbn/postgresql:9.4   "/start"            5 seconds ago       Exited (1) 4 seconds ago                       postgresql-gitlab

> docker logs 1334c50d0e2f
find: `/var/lib/postgresql/[0-9].[0-9]/main': No such file or directory
Initializing database...
initdb: could not create directory "/var/lib/postgresql/9.4/main": Permission denied
```

Any idea how can I fix it or apply some workaround?

Thank you

**Comment by sameersbn** [comment]
@mrh666 I think this is has something to do with shared folders on a vm. This is a very common issue. Please take a look a https://github.com/bitnami/bitnami-docker-mariadb/issues/13, you might find some pointers in there.

**Comment by mrh666** [comment]
@sameersbn I use boot2docker, not a Vagrant. But anyway issue the same. I moved to docker 1.7. Trying different directories: /opt/postgres, /tmp/postgres. Same issues. Any kind of directory permissions, privileged mode doesn't help.

Some other ideas?

**Comment by sameersbn** [comment]
@mrh666 this is the only suggestion I can give :smile: https://github.com/sameersbn/docker-postgresql/issues/22#issuecomment-113152432

**Comment by divmgl** [comment]
Did you have any luck resolving this issue?

**Comment by mrh666** [comment]
Nope. You can't have ext2/3/4 fs on Mac...

**Comment by divmgl** [comment]
@mrh666 I ended up having to create a Docker volume. I'll likely switch to a data-only container today. Pretty annoying.

**Comment by mrh666** [comment]
divmgl, right. I believe this is only solution.

**Comment by Sapphire64** [comment]
Had the same issue for one simple reason: I had a docker machine with volume mounted to a vagrant folder. That vagrant folder was actually mounted to vagrant linux machine from OSX host machine. I just changed docker's volume to point to random folder which is not mounted from OSX and it solved my problem.
