### ISSUE TITLE
Creating a super-user?

### ISSUE THREAD

**Issue by girvo** [sameersbn/docker-postgresql#37]
Hey there,

Quick question that I can't seem to work out from the docs. How does one create a super-user? `DB_USER` and `DB_PASS` seem to create a regular user.

Cheers,
Josh

**Comment by sameersbn** [comment]
at the moment no password is set to the superuser `postgres` as a result of which you can only connect to the server using the unix domain socket. You can login to the server as `postgres` user using docker exec  and create add the required privileges to a user.

**Comment by girvo** [comment]
Beautiful, that's the workaround I was hoping existed :) thanks! Great work on this Dockerfile by the way, it's an absolute lifesaver.

**Comment by sameersbn** [comment]
Glad that you find it useful.
