### ISSUE TITLE
how do i import a database into the container?

### ISSUE THREAD

**Issue by babatundebusari** [sameersbn/docker-postgresql#39]
Lets say i have a database database.psql and want to import into the container
How do i achieve this?

Thanks

**Comment by sameersbn** [comment]
You will need to do this manually.

1. start container with by specifying a user and database to create
2. copy the `.psql` file into the container using `docker cp`
3. exec into the container and restore the dump.

**Comment by babatundebusari** [comment]
i was thinking that if the there is persistent storage to host `-v /opt/postgresql/data:/var/lib/postgresql` then can i just copy the .psql file to the location on the host and restart container?
I just need to know the location to place the .psql file

Will that work or i have to use `docker cp` ?

Thanks

**Comment by sameersbn** [comment]
yes that will work as well.

**Comment by babatundebusari** [comment]
Where do i place the .psql file
and do i still need to do psql import or what do you mean by step 3. above "Step 3. exec into the container and restore the dump."?

Thanks

**Comment by sameersbn** [comment]
the .psql file is a dump right. You need to exec into the container and 
restore the dump. Please refer to postgresql docs for the procedure to 
restore dumps.

On Wednesday 21 October 2015 09:50 PM, babatundebusari wrote:
> Where do i place the .psql file
> and do i still need to do psql import or what do you mean by step 3.
> above "Step 3. exec into the container and restore the dump."?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sameersbn/docker-postgresql/issues/39#issuecomment-149950319>.
>

-- 
Sameer Naik

w: http://www.damagehead.com e: sameer@damagehead.com

**Comment by babatundebusari** [comment]
got it

Thanks
