### ISSUE TITLE
Account problems

### ISSUE THREAD

**Issue by LongTaiJun** [sameersbn/docker-postgresql#43]
Will enable the default postgres account, or add multiple accounts?

**Comment by sameersbn** [comment]
I dont understand your question!

**Comment by LongTaiJun** [comment]
I would like landing postgres this account, ask how the allocation?

**Comment by sameersbn** [comment]
By default the `postgres` user is not assigned a password, thus only allowing login locally (i.e. using `docker exec`). You can set a password for the `postgres` use using `docker exec` if required.

**Comment by LongTaiJun** [comment]
This project is the master copy from the stream, what can be combined pgpool use it? I did not do succeed -

**Comment by LongTaiJun** [comment]
https://github.com/BetterVoice/pgpool2-container
I used this project, but how does not work, please, under the guidance, thank you.

**Comment by sameersbn** [comment]
Looks like the pgpool2 container required administrative access to the postgresql server. This means that you will need to set a password for the `postgres` user:

Login to the postgresql server using

```bash
docker exec -it postgresql sudo -u postgres psql
```

and set a password for the `postgres` user.

**Comment by LongTaiJun** [comment]
Thank you for your answer, I'm going to try next.

**Comment by sameersbn** [comment]
In the `latest` build I have added the `PG_PASSWORD` parameter to set password for the `postgres` user.

**Comment by LongTaiJun** [comment]
pgpool connection fails, it is my reason, get it working, but still thank you ~

**Comment by sameersbn** [comment]
Closing issue. Reopen if you continue to face problems.
