### ISSUE TITLE
docker 9.5 support

### ISSUE THREAD

**Issue by bobcolner** [sameersbn/docker-postgresql#45]
appreciate all your efforts!

**Comment by bobcolner** [comment]
I meant postgres 9.5 support!

**Comment by sameersbn** [comment]
Now that 9.5 has been released. I will create a new release after some initial tests.

**Comment by dddpaul** [comment]
Hi. When new release for PostgreSQL 9.5 will be ready?

**Comment by sameersbn** [comment]
Will try to get a new release done this weekend. Last time I tried there were some issues migrating existing data. Hopefully will get it figured out :smile:

**Comment by viper0131** [comment]
Hi Sameer, any update on a 9.5 release?

**Comment by kusmierz** [comment]
@sameersbn any news? :)

**Comment by fabiomartins87** [comment]
@sameersbn Great work this this docker image! Do you have an estimate for the 9.5 release?

**Comment by viper0131** [comment]
Hello @sameersbn,

It's very quiet, do you have any news on a 9.5 release? We are using your 9.4 release with great pleasure, but we want to move to the 9.5 release soon. 

Please let us know what your plans are,

**Comment by sameersbn** [comment]
Hey guys, sorry it took so long, we finally have the `9.5` release.
I did not face the migration issues that I initially found. Guess it was some issue in the PostgreSQL that may have been resolved.
