### ISSUE TITLE
Sudoers_policy

### ISSUE THREAD

**Issue by cescoferraro** [sameersbn/docker-postgresql#48]
It works fine on my macbook but fail on ubuntu 14.04 server like this.
```
$ sudo docker  run sameersbn/postgresql:9.4-11                                                                         
Initializing datadir...
Initializing certdir...
Initializing logdir...
Initializing rundir...
Initializing database...
sudo: error in /etc/sudo.conf, line 0 while loading plugin `sudoers_policy'
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
```

**Comment by sameersbn** [comment]
looking at this post http://askubuntu.com/questions/637432/sudo-comes-up-with-an-error-cannot-run-anything-as-root, it is possible that the postgresql image has got corrupted during the pull. Can you try removing the image and re-pulling?

**Comment by cescoferraro** [comment]
@sameersbn yes! It was a currupted image
