### ISSUE TITLE
Postgis installation and setup

### ISSUE THREAD

**Issue by phlegx** [sameersbn/docker-postgresql#51]
Hi,

I wanted to ask if it is possible to install and setup postgis with this docker image. I did add the following to my Dockerfile that uses your image:

```
# Install postgis
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  postgis \
  postgresql-9.4-postgis-2.1 \
  && rm -rf /var/lib/apt/lists/*
```

However when the database is created via my rails app, I get the following error:

```
PG::UndefinedFile: ERROR:  could not access file "$libdir/postgis-2.2": No such file or directory
: CREATE EXTENSION IF NOT EXISTS postgis 
```

This file is obviously defined in the the file:

```
/usr/share/postgresql/9.4/extension/postgis.control
```

thanks in advance!

**Comment by phlegx** [comment]
Uh I already solved it by installing:

```postgresql-9.4-postgis-2.2```

instead of

```postgresql-9.4-postgis-2.1```

**Comment by sameersbn** [comment]
fyi, the https://github.com/sameersbn/docker-postgresql/tree/postgis-extension-finalization branch consists of ongoing postgis support work. I am not sure whether it will be merged in its current state, but yes it works.
