### ISSUE TITLE
ZFS can cause the container to fail on setfacl

### ISSUE THREAD

**Issue by ejstacey** [sameersbn/docker-postgresql#52]
This isn't something that is strictly the fault of docker-postgresql, but maybe it should have a mention somewhere?  Or you could test for setfacl capability before trying to run the command?  I'm not sure, but I thought I'd record it here.

The situation is that when using the zfs docker filesystem driver, it uses cloning and snapshots from zfs natively.  ZFS (on Linux, at least) has the capability to not use POSIX ACLs.  This causes a setfacl on /etc/resolv.conf to fail in the container, which makes the container fail.

The fix is to set "acltype" to "posixacl" on the underlying zfs filesystem (and restart the container).  This allows setfacl to work.

Thanks,
-Eric

**Comment by TimCook1** [comment]
So, again "not my problem" - but I'd agree.  This actually goes beyond ZFS - synology also builds their system without setfacl compatibility.  So 9.4-11 is the last compatible version of postgresql that works on synology systems.

Any chance you can put in a check for setfacl compatibility, and if it isn't there still continue?  The setfacl does not appear to be required for this to work, more of a "nice to have".

**Comment by gopeter** [comment]
:+1:

**Comment by gopeter** [comment]
I just wrote a little check for `setfacl` compatibility. Hope this MR gets merged soon, because Synology users can't use GitLab 8.6.0 without this fix :)

**Comment by TimCook1** [comment]
Any idea when this fix will be in a published release?

**Comment by sameersbn** [comment]
Tagged a new release `9.4-18` :)

On Wednesday 30 March 2016 10:34 PM, TimCook1 wrote:
> Any idea when this fix will be in a published release?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/sameersbn/docker-postgresql/issues/52#issuecomment-203528313>
>

-- 
Sameer Naik

w: http://www.damagehead.com e: sameer@damagehead.com

**Comment by queglay** [comment]
I see something similar to this on qnap...
```
Initializing datadir...                                                                                                             
Initializing certdir...                                                                                                             
Initializing logdir...                                                                                                              
Initializing rundir...                                                                                                              
Setting resolv.conf ACLs...                                                                                                         
setfacl: /etc/resolv.conf: Operation not supported                                                                                  
Initializing database...       
```
