### ISSUE TITLE
Creating a NEW DB in a running PostgreSQL container

### ISSUE THREAD

**Issue by pascalandy** [sameersbn/docker-postgresql#58]
Hello Sameer,

I'm using the docker-postgresql with Wordpress and it work very well so far :)

At the moment, I'm running Gitlab 7 on bare-metal and I found your docker-gitlab project. Great it's time to upgrade.

I have a question about using multiple applications with the SAME postgresql container.

### CONTEXT

In this section: https://github.com/sameersbn/docker-gitlab#quick-start, we can read 

Step1 ...

```
docker run --name gitlab-postgresql -d \
    --env 'DB_NAME=gitlabhq_production' \
    --env 'DB_USER=gitlab' --env 'DB_PASS=password' \
    --env 'DB_EXTENSION=pg_trgm' \
    --volume /srv/docker/gitlab/postgresql:/var/lib/postgresql \
    sameersbn/postgresql:9.4-17
```
... and from this section: https://github.com/sameersbn/docker-redmine#quick-start

Step1 ...

```
docker run --name=redmine -d \
  --link=postgresql-redmine:postgresql --publish=10083:80 \
  --env='REDMINE_PORT=10083' \
  --volume=/srv/docker/redmine/redmine:/home/redmine/data \
  sameersbn/redmine:3.2.1-2
```

And the same structure applies for Discourse. So far so food when you want to launch a new DB per service.

### Question

What if I'm actually running docker-postgresql and I want to launch Gitlab install WITHOUT creating a new postgresql container ?

Could you share how we could create a DB_NAME / DB_USER / DB_PASS into a running postgresql container ?

I feel we need a new container companion (pgsql-DBcreation) that will:
- listen for ENV variables we want to introduce into postgresql
- log into the active postgresql container
- run some bash script commands to create the DB_NAME / DB_USER / DB_PASS / etc
- show what was created
- exit from postgresql container 
- stop pgsql-DBcreation

Maybe there is already some docker run project that does this task but I haven't found it yet. 

Lastly, thank you so much for all your work, it very appreciated. 

Many Cheers!
Pascal

**Comment by sameersbn** [comment]
@pascalandy docker-postgresql allows you to create multiple database by specifying a comma separated list of database in `DB_NAME`. However only a single user will be granted access to all the database. I agree this is not ideal.

Second option is to stop the container and relaunch with new `DB_NAME`,  `DB_USER` and other parameters. Since you would use persistence, the database and user created in the first run will continue to exist while the new user/database is being created in the second run.

Finally option it to login to the running container and manually fire SQL queries to create users/databases, etc.

p.s. you will need to specify the `DB_NAME`, `DB_USER` and `DB_PASS` parameters in the redmine and gitlab container env and not rely on automatic discovery of these from docker links.

It should be pretty easy to construct a companion tool for database and user creation by creating a wrapper around `psql`, which appears to be pointless when you can just as easily use `psql` client tool.

**Comment by pascalandy** [comment]
Second option works for DEV but not in PROD. 

So I'll go manually via psql but it would be really great to define ENV via compose but launching any kind of services that need a new DB in PgSQL. 

Thanks for you thoughts!

**Comment by sameersbn** [comment]
> It would be really great to define ENV for creating a new DB_NAME, DB_USER and DB_PASS via compose

I don't completely understand the use-case.

**Comment by pascalandy** [comment]
In the docker-compose of the container companion (pgsql-DBcreation), it would be really great to define ENV that will create a new DB_NAME, DB_USER and DB_PASS, before launching any kind of services that need a new DB in PgSQL.

Make sense?

**Comment by pascalandy** [comment]
This is what I was looking for :) Maybe you can add a section about this in the README

**First**
`docker exec -it postgresql-master sudo -u postgres psql`

Then, within the container, create a new db, user, pass like this:

```
CREATE USER g99999101_136 SUPERUSER PASSWORD '784ba188050f88a266280f8a63d0c010b363837ec391';
CREATE DATABASE g99999101_136;
GRANT ALL PRIVILEGES ON DATABASE g99999101_136 TO g99999101_136;
```

Quit the container:

`\q`

Cheers!

**Comment by pascalandy** [comment]
Now, I'd like to do this within one big copy-paste command. I don't know how to do this yet and we quit the shell and go within the container.

The goal is to add a new db, user, pass WITHOUT stopping the master DB. Ideas?

**Comment by sameersbn** [comment]
>  docker exec -it postgresql-master sudo -u postgres psql

This is mentioned in the Quickstart section. From here you can administer the postgresql server. You think we should add examples to create users, database, etc. from the psql command line?

> The goal is to add a new db, user, pass WITHOUT stopping the master DB. Ideas?

Try

```bash
docker exec -it postgresql-master psql -U postgres -c \
  "CREATE USER user1001 SUPERUSER PASSWORD '98giu2b3eqd98gub98gub3q'; \
   CREATE DATABASE user1001; \
   GRANT ALL PRIVILEGES ON DATABASE user1001 TO user1001;"
```

**Comment by pascalandy** [comment]
Will try asap. I'll let you know soon. 
Thanks for the follow up!

![gustavo-art-water-sun-7LLviNCYAmMWA](https://media4.giphy.com/media/7LLviNCYAmMWA/giphy.gif)

**Comment by pascalandy** [comment]
There is few glitch in your code above but the key I was missing is this:

```
docker exec -it postgresql sudo -u postgres psql -c \
        "CREATE DATABASE $ENV_DEPLOY_ID;"
```

I actually went further with the read than wait for user input and an auto-generated password.
In this setup DEPLOY_ID is the DB_NAME and the USER. 

Hope it can be useful to everyone!

```
    echo '' && echo '' && \
            echo "/te - create db" && \
            echo "Every new DEPLOY_ID must have its own db" && \
            echo "PikWi says: BEGIN JOURNEY - Create a new DB for this a new DEPLOY_ID" && echo '' && \
            echo "PikWi says: What is the DEPLOY_ID? Waiting your input..." && \
    read ENV_DEPLOY_ID && echo '' && \
            echo "PikWi says: Let's generate a fancy password" && \
    ENV_TMP1=`strings /dev/urandom | grep -o '[[:alnum:]]' | head -n 14 | tr -d '\n';` &&
    ENV_TMP2=`date +%s | sha256sum | base64 | head -c 15 ;` &&
    ENV_TMP3=`tr -cd '[:alnum:]' < /dev/urandom | fold -w12 | head -n1` &&
    ENV_DB_PASSWORD="$ENV_TMP2$ENV_TMP3$ENV_TMP1" && echo '' && \
            echo "PikWi says: USER & DB are named as per: $ENV_DEPLOY_ID" && \
            echo "PikWi says: Let's create the database. Allow about 10 seconds." && echo '' && \
    docker exec -it postgresql sudo -u postgres psql -c \
        "CREATE DATABASE $ENV_DEPLOY_ID;" && \
        sleep 6 && \
            echo "PikWi says: Wait is over. Let's grant all privileges on database $ENV_DEPLOY_ID" && \
    docker exec -it postgresql sudo -u postgres psql -c \
        "CREATE USER $ENV_DEPLOY_ID SUPERUSER PASSWORD '$ENV_DB_PASSWORD'; \
        GRANT ALL PRIVILEGES ON DATABASE $ENV_DEPLOY_ID TO $ENV_DEPLOY_ID;" && \
        sleep 4 && echo '' && \
        echo "PikWi says: W-A-R-N-I-N-G! Save this password:" && \
        echo "PikWi says: $ENV_DB_PASSWORD" && echo '' && \
        echo "PikWi says: Next, let's create the S3 bucket for $ENV_DEPLOY_ID" && \
        echo ''
```

Cheers!
twitter.com/_pascalandy

**Comment by sameersbn** [comment]
should we close this issue?

**Comment by pascalandy** [comment]
Sure

**Comment by nodecentral** [comment]
Hi, I’m very new to all this, but I tried the above and I got the following error..

````
[/] # docker exec -it PostgreSQL-bridge sudo -u postgres psql -c \
> "CREATE DATABASE $ENV_DEPLOY_ID;"
OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: exec: "sudo": executable file not found in $PATH: unknown
[/] #
````
