### ISSUE TITLE
pg_dump in shell

### ISSUE THREAD

**Issue by kprinssu** [sameersbn/docker-postgresql#60]
I am currently trying to set up a Gitlab CI environment. I currently have a Rails project that requires the use of pg_dump. Rails currently tries to create a dump of the database by executing pg_dump as a shell command. 

The issue is that Docker does not expose pg_dump in the shell even though the `postgresql-client`  gets installed. The solution I found was to execute a `apt-get install postgresql-client`. Is there a proper way of aliasing the command?

**Comment by sameersbn** [comment]
@kprinssu I don't understand your question and whether its related to this image at all. Do you intend to run `pg_dump` in the postgresql container?? My guess it probably not. However if you wanted to then yes `pg_dump` is present in the image.

> The solution I found was to execute a apt-get install postgresql-client. Is there a proper way of aliasing the command?

In which container are you doing this?

**Comment by kprinssu** [comment]
I want to run `pg_dump`. I want to run it within Gitlab's Runner. I assume that it spins up a new Docker container to run any builds.

What I am trying to do is execute `pg_dump` from within the Gitlab Runner.
My `.gitlab-ci.yml` has a test to see if `pg_dump` exists or not:
```
before_script:
  - ruby -v
  - pg_dump --version
```

The Gitlab runner returns a command not found error:
```
$ pg_dump --version
/bin/bash: line 31: pg_dump: command not found
```

**Comment by sameersbn** [comment]
You need to either create a image using the gitlab-runner image with the required dependencies or use the docker executor to run a container with the required configuration.

**Comment by kprinssu** [comment]
I used the official rails image from hub.docker.com and seems to work fine now.
