### ISSUE TITLE
cannot use and GUI to access the master

### ISSUE THREAD

**Issue by luizkowalski** [sameersbn/docker-postgresql#65]
I have the following config on docker-compose

```
postgres-master:
  image: sameersbn/postgresql:9.4-21
  container_name: postgres-master
  restart: always
  environment:
    - DEBUG=false
    - DB_USER=postgres
    - DB_PASS=postgres
    - DB_NAME=test
    - REPLICATION_USER=repluser
    - REPLICATION_PASS=replpass
  ports:
    - "5432:5432"
```
when I try to access this host with some GUI, like pgAdmin, I get the following error

```
postgres-master    | FATAL:  password authentication failed for user "postgres"
postgres-master    | DETAIL:  User "postgres" has no password assigned.
postgres-master    | 	Connection matched pg_hba.conf line 94: "host all all 0.0.0.0/0 md5"
postgres-master    | FATAL:  password authentication failed for user "postgres"
```
seems like it is impossible due to docker's network behaviour or I'm missing some extra config. what can be?

**Comment by sameersbn** [comment]
@luizkowalski sorry at the moment you cannot set a password for the `postgres` user using the env variables. As a workaround you would need to exec into the container `docker exec -it <container-name> psql -U postgres` and then set a password.

I will add some logic to set the postgres password in future releases. Thanks for reporting.

**Comment by luizkowalski** [comment]
worked! thanks for the response
