### ISSUE TITLE
PG_TRUST_LOCALNET=true not set properly

### ISSUE THREAD

**Issue by CzechJiri** [sameersbn/docker-postgresql#68]
looking at pg_hba.conf inside the container, when using PG_TRUST_LOCALNET=true  `host all all samenet trust` is set at the very end below `host all all 0.0.0.0/0 md5` which makes the rule `host all all 0.0.0.0/0 md5` run first and thus never evaluates the `host all all samenet trust` 

instead of this
```
...
host all all 0.0.0.0/0 md5
host all all samenet trust
```

the file should look like this

```
...
host all all samenet trust
host all all 0.0.0.0/0 md5
```

**Comment by sameersbn** [comment]
thanks for the report. working on a fix.
