### ISSUE TITLE
Having an Input/output error

### ISSUE THREAD

**Issue by wurdum** [sameersbn/docker-postgresql#73]
Hi guys,

I'm receiving an error when creating container:

```
docker run --name=postgresql -d \
--env='DB_NAME=redmine' \
--env='DB_USER=redmine' --env='DB_PASS=pass' \
--volume=/Users/wurdum/Code/containers/redmine/postgresql:/var/lib/postgresql \
sameersbn/postgresql:9.4-22
```

Docker logs shows next:

```
Initializing datadir...
Initializing certdir...
Initializing logdir...
Initializing rundir...
Setting resolv.conf ACLs...
Initializing database...
Configuring hot standby...
‣ Setting postgresql.conf parameter: wal_level = 'hot_standby'
‣ Setting postgresql.conf parameter: max_wal_senders = '16'
‣ Setting postgresql.conf parameter: checkpoint_segments = '8'
sed: read error on /var/lib/postgresql/9.4/main/postgresql.conf: Input/output error
```

Using `Docker version 1.12.0-rc4, build e4a0dbc, experimental`.
Please let me know if I can provide any additional info.

**Comment by pschuegr** [comment]
FYI this has been reported to Docker, see here:

https://forums.docker.com/t/mounted-host-directories-not-compatible-with-postgresql/18322
https://forums.docker.com/t/writing-issue-with-docker-beta-on-mac-mounted-volume-from-dropbox/17754/6

**Comment by LongLiveCHIEF** [comment]
@wurdum can we close this?

**Comment by wurdum** [comment]
Yes, it's no longer relevant
