### ISSUE TITLE
Tag 9.4-24 not found in repository

### ISSUE THREAD

**Issue by sinc59** [sameersbn/docker-postgresql#74]
Hello,
when i try to pull your docker image, i get this error "Tag 9.4-24 not found in repository"
In fact, the image in the docker registry have the "latest" tag is it normal ?
(Many documentations have reference to this tag..)

Regards,

**Comment by SolidNerd** [comment]
Hey, 
i have the same issue the problem will be resolve when the git tag for `9.4-24` will be added.

**Comment by sameersbn** [comment]
Fixed now. Sorry for the inconvenience.
