### ISSUE TITLE
TimeZone

### ISSUE THREAD

**Issue by movcale** [sameersbn/docker-postgresql#75]
Hello,

How I can set default time zone for postgres container?

Is it TZ variable available, as you did for docker-redmine container ?
https://github.com/sameersbn/docker-redmine/blob/1b397e90a9a615b97d81e64d143ea2ebeaacb01d/docker-compose.yml#L15

Thanks

**Comment by sameersbn** [comment]
https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=cbf4f6bb34fc77f6698ff036e16e0739357cedd0 indicates that postgresql ignores the TZ env variable.

**Comment by sameersbn** [comment]
you may wanna take a look at http://stackoverflow.com/questions/6663765/postgres-default-timezone

**Comment by sameersbn** [comment]
also https://www.postgresql.org/docs/9.1/static/libpq-envars.html, see `PGTZ`

**Comment by movcale** [comment]
Thank you. Valuable answers!

**Comment by sameersbn** [comment]
closing the issue. If you were able to find the answer to your query then please consider sharing it here. thanks.
