### ISSUE TITLE
utf-8

### ISSUE THREAD

**Issue by Antoine-O** [sameersbn/docker-postgresql#81]
Hello there !

how to force utf-8 encoding ?

thx

**Comment by LongLiveCHIEF** [comment]
https://github.com/sameersbn/docker-postgresql#command-line-arguments

**Comment by Antoine-O** [comment]
Oh sorry, completely forgotten thisbissue. The problem was in java. I forced utf8 in java and evrythibg wotked like a charm.

**Comment by LongLiveCHIEF** [comment]
ahh... good call!
