### ISSUE TITLE
PG_RUNDIR volume definition

### ISSUE THREAD

**Issue by SlevinBE** [sameersbn/docker-postgresql#85]
I'm trying to understand why PG_RUNDIR was defined as a volume. Was there a specific reasoning for this?
I'm not an expert in Postgres, so I might be overlooking something here, but isn't this directory only used to capture active sockets (so not something requiring a persistent volume)?

**Comment by LongLiveCHIEF** [comment]
It's not a postgres thing, it's a docker thing. It makes that volume available to be utilized when performing container linking.
