### ISSUE TITLE
Doesn't start anymore after restarting the container 

### ISSUE THREAD

**Issue by lenovouser** [sameersbn/docker-postgresql#93]
Also there are no logs. Only this in a loop:

```
postgresql    | Initializing datadir...
postgresql    | Initializing certdir...
postgresql    | Initializing logdir...
postgresql    | Initializing rundir...
postgresql    | Setting resolv.conf ACLs...
postgresql    | pg_ctl: could not start server
postgresql    | Examine the log output.
```

If I look in my data directory there is no `postgresql-9.6-main.log`, only this:

```
pg_upgrade_dump_1.log
pg_upgrade_dump_12377.log
pg_upgrade_dump_27219.log
pg_upgrade_dump_30632.log
pg_upgrade_dump_43172.log
pg_upgrade_internal.log
pg_upgrade_utility.log
pg_upgrade_dump_1.custom
pg_upgrade_dump_12377.custom
pg_upgrade_dump_27219.custom
pg_upgrade_dump_30632.custom
pg_upgrade_dump_43172.custom
pg_upgrade_dump_globals.sql
pg_upgrade_server.log
```

None of these contain any information on why it isn't starting. I also can't `bash` into the container fast enough because it crashes nearly immediately.

**Comment by lenovouser** [comment]
This also happens when I start a totally new instance of the container with a empty data directory

**Comment by derkd** [comment]
what if you do 
```
service postgresql start
```

After restarting the service I get a permission denied on a certificate in my certificate dir. After every reboot it returns the permissions.

Shouldn't this:

```
create_certdir() {
  echo "Initializing certdir..."
  mkdir -p ${PG_CERTDIR}
  [[ -f ${PG_CERTDIR}/server.crt ]] && chmod 0644 ${PG_CERTDIR}/server.crt
  [[ -f ${PG_CERTDIR}/server.key ]] && chmod 0640 ${PG_CERTDIR}/server.key
  chmod 0755 ${PG_CERTDIR}
  chown -R root:${PG_USER} ${PG_CERTDIR}
}
```

be changed into this:
```
create_certdir() {
  echo "Initializing certdir..."
  mkdir -p ${PG_CERTDIR}
  [[ -f ${PG_CERTDIR}/server.crt ]] && chmod 0644 ${PG_CERTDIR}/server.crt
  [[ -f ${PG_CERTDIR}/server.key ]] && chmod 0640 ${PG_CERTDIR}/server.key
  chmod 0755 ${PG_CERTDIR}
  chown -R ${PG_USER}:${PG_USER} ${PG_CERTDIR}
}
```

???

**Comment by lenovouser** [comment]
It was some weird issue with docker disk space. I had 1.8 TB of 2 TB free on the actual disk but built like 90GB's worth of containers 2-3 hours before which were laying around in `/var/lib/docker`. Somehow Docker didn't like that even though there was plenty more space available.

**Comment by thmsaurel** [comment]
Hi, I have the same issue on my docker installation. how do you fix it ?

**Comment by stephenmoloney** [comment]
I'm getting something similar - randomly - everything was working fine before. No idea how to fix it - anyone?

**Comment by stephenmoloney** [comment]
I really don't know what happened but removing the docker volume manually was the only thing that worked for me. 

`sudo rm -R /srv/docker/postgresqll`

NOTE: this will completely wipe your data. I was only using the container for some tests/development.

**Comment by iONsky** [comment]
I had the same problem. After GitLab kind of froze when performing backups I had to hard shutdown my server. That somehow caused PostgreSQL to become corrupt.

After spending hours of researching I finally was able to solve it.

1. As usual make a backup of the data directory.
2. Start the PostgreSQL container with `docker-compose run --rm postgresql`.
3.  Now you have to be quick. Open a new terminal session (you can do this before) and execute `docker exec -it gitlab_postgresql_run_1 sudo -u postgres bash` (the name of the container can vary. Check `docker ps` to see the name of the running container).
4. Reset the transaction logs with `/usr/lib/postgresql/9.6/bin/pg_resetxlog -f /var/lib/postgresql/9.6/main` (see this [StackOverflow answer](https://stackoverflow.com/a/14716579)).
5. Switch back to the original terminal session and check the logs. You should see that the database will now start correctly. 

Hope that helps anyone.

**Comment by zbence** [comment]
iONsky One doesn't need to be quick just smart :) 
```
docker  run -d --name postgres-gitlab -e DB_USER=gitlab2 -e DB_PASS=git1a3-d3v-pa22w0rd -e DB_EXTENSION=pg_trgm -e DB_NAME=gitlabhq_production -v /var/nfs/p
ostgres-gitlab-2:/var/lib/postgresql   sameersbn/postgresql:9.6-2 -d 5 && sleep 1 && docker exec -it postgres-gitlab sudo -HEu postgres /usr/lib/postgresql/9.6/bin/pg_resetxlog -f /var/lib/p
ostgresql/9.6/main
```

**Comment by zbence** [comment]
iONsky don't need to be quick just chain the commands one after other:
```
docker  run -d --name postgres-gitlab sameersbn/postgresql:9.6-2 -d 5 && sleep 1 && docker exec -it postgres-gitlab sudo -HEu postgres /usr/lib/postgresql/9.6/bin/pg_resetxlog -f /var/lib/p
ostgresql/9.6/main
```

**Comment by 0x646e78** [comment]
Just popping in incase anyone has this happen on 10, which I've had just now. Following worked for me (executed within the container with the data volume mounted) - as per @iONsky but with the new `resetwal` command.

`/usr/lib/postgresql/10/bin/pg_resetwal -f /var/lib/postgresql/10/main`
