### ISSUE TITLE
Postgis extension

### ISSUE THREAD

**Issue by borgdrone7** [sameersbn/docker-postgresql#99]
Hi,
Seems that postgis extension does not work, do I need to make some extra steps? Where can I check more detailed reason of why it failed:
+ psql -U postgres -d geoagent -c 'CREATE EXTENSION IF NOT EXISTS postgis;'
‣ Loading postgis extension...

Container just stops after that line.

**Comment by borgdrone7** [comment]
figured it out

**Comment by fmartingr** [comment]
For those coming here from the same error, I solved it installing the `postgresql-${PG_VERSION}-postgis-2.3-scripts` package along with the postgis one.
